---
kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    app: redis
    role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: accountid.dkr.ecr.eu-west-1.amazonaws.com/redis:latest
        ports:
        - name: redis-server
          containerPort: 6379